---
- name: Deploy Heimdall with a dedicated named volume
  hosts: rocky_nodes
  become: true

  vars:
    heimdall_container_name: heimdall
    heimdall_image: lscr.io/linuxserver/heimdall:latest
    heimdall_port: 8080

  tasks:
    - name: Create Docker volume for Heimdall
      docker_volume:
        name: "{{ heimdall_container_name }}"
        state: present

    - name: Pull Heimdall image
      docker_image:
        name: "{{ heimdall_image }}"
        source: pull

    - name: Run Heimdall container with named volume
      docker_container:
        name: "{{ heimdall_container_name }}"
        image: "{{ heimdall_image }}"
        restart_policy: unless-stopped
        state: started
        volumes:
          - "{{ heimdall_container_name }}:/config"
        ports:
          - "{{ heimdall_port }}:80"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/Athens"
