---
- name: Provision Docker Runtime on Rocky Linux
  hosts: rocky_nodes
  become: true
  vars:
    docker_packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  tasks:
    - name: Ensure prerequisite packages are present
      package:
        name: "{{ docker_packages }}"
        state: present

    - name: Add Docker official repository
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker Engine and companion stack
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user to docker group (optional)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
